### ISSUE TITLE
[Test/result] 모바일뷰

### ISSUE THREAD

**Issue by yezgoget** [mnxmnz/colfume-frontend#220]
## 💡 이슈 제목
![image](https://user-images.githubusercontent.com/55784772/126441680-f28f30d4-9b6b-47c1-9495-4b5c5d3433c2.png)
## ✨ 이슈 설명

- [x] matching color 까지 텍스트 정렬
- [x] 이미지 불러오기 (왜 안불러와져...ㅂㄷㅂㄷ)
- [x] 버튼 2개 
- [x] description
- [x] matching color white배경색 흰색으로 하기

## 🎯 이슈 생성 후 확인 내용
- [x] 이슈 제목 확인 
- [x] Assignees 설정 
- [x] Labels 설정 
- [x] Projects 설정

**Comment by mnxmnz** [comment]
@yezgoget 갓예지님 데모데이 이후에도 이슈 생성하는 모습.. 완전 멋져요..! 존경합니다.. ❤👍

> 이미지 불러오기 (왜 안불러와져...ㅂㄷㅂㄷ)

이 부분 정말 귀엽네요.. 저희 같이 해결해요..! 아자자! 🚀
