### ISSUE TITLE
[Project] fix: 프로젝트 이슈 해결하기

### ISSUE THREAD

**Issue by mnxmnz** [mnxmnz/colfume-frontend#92]
## 💡 이슈 제목
[Project] fix: 프로젝트 이슈 해결하기

## ✨ 이슈 설명
- [x] Main 화면에서 새로고침 했을 때 이슈
  - 새로고침을 눌렀을 때 window.width 의 초깃값인 0이 할당되는 에러
  - localstorage 값으로 새로고침 했을 때 0이 되는 것은 해결
  - 그러나 처음 진입했을 때 useState의 초깃값 문제 해결 필요함

- [x] Main 화면에서 배너 반응형 이슈
  - 텍스트 위치와 사진의 높이를 고정하고 사진 반응형 변경해서 해결하기

- [x] Product Detail width 값 지정 방법 변경
  - 전체적인 width 값 지정이 아닌 반응형 여백 지정 방법으로 변경하기

- [x] Test/Questions 문제 부가 설명 부분 텍스트 확정
  - 기획에게 2번 문제 설명 두 줄이 아닌 한 줄로 내용 변경 요청하기

- [x] PC 뷰 & 모바일 뷰 사이 반응형 지정
  - 디자인 유지하면서 크기 깨지지 않게 수정

- [x] 모바일 반응형 크기 이슈
  - 모바일 반응형 크기 피그마 기준인 375로 변경하기

- [x] 폰트 추가하기
  - 구글 폰트에 없는 폰트는 따로 검색해서 추가하기

- [x] 코드 전체적으로 살펴보기
  - 중복 코드 제거하기

## 🎯 이슈 생성 후 확인 내용
- [x] 이슈 제목 확인 
- [x] Assignees 설정 
- [x] Labels 설정 
- [x] Projects 설정

**Comment by yezgoget** [comment]
....갓민지.... 못하는게 뭔가요

**Comment by mnxmnz** [comment]
> ....갓민지.... 못하는게 뭔가요

예지님 자기소개 멈춰주세요...!
