### ISSUE TITLE
[Project] feat: 배포 전 설정 사항

### ISSUE THREAD

**Issue by mnxmnz** [mnxmnz/colfume-frontend#93]
## 💡 이슈 제목
[Project] feat: 배포 전 설정 사항

## ✨ 이슈 설명
- [x] meta data 등록하기
  - 테스트 결과마다 다른 data 등록은 조금 더 확실하게 알아보기
    - => 알아본 결과 SSR이 필요하다고 해서 앱잼 기간 동안에는 포기!
    - 기획 + 디자인에게 대표 meta data 하나만 받으면 됨
    - 관련 자료1: [next/head](https://nextjs.org/docs/api-reference/next/head)
    - 관련 자료2: [Next.js에서 head 태그를 조작하는 멋진 방법](https://wonit.tistory.com/358?category=829651)
    - 관련 자료3: [NEXT HEAD 에 대하여](https://velog.io/@cyranocoding/NEXT-HEAD-%EC%97%90-%EB%8C%80%ED%95%98%EC%97%AC)
  - 기획 + 디자인에게 meta data list 전달하기

- [x] 도메인 구입해서 등록하기
  - 저번 도메인 등록처럼 CNAME 등 설정하기
  - 기획에게 도메인 목록 전달하기

## 🎯 이슈 생성 후 확인 내용
- [x] 이슈 제목 확인 
- [x] Assignees 설정 
- [x] Labels 설정 
- [x] Projects 설정

**Comment by yezgoget** [comment]
완전..완전 짱이에요 사랑해요

**Comment by mnxmnz** [comment]
> 완전..완전 짱이에요 사랑해요

내가 더 💗💗💗
